### ISSUE TITLE
'cycler' (dependency of matplotlib) missing?

### ISSUE THREAD

**Issue by oliveroxtoby** [FreeCAD/FreeCAD-AppImage#17]
Running the latest AppImage on my system (FreeCAD_0.19.16207_Conda_Py3Qt5_glibc2.12-x86_64.AppImage) I get the following error if I try to activate the Plot workbench:
`matplotlib not found, Plot module will be disabled`

Trying to import matplotlib in the python console suggests that the 'cycler' package is not present:
```
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type 'help', 'copyright', 'credits' or 'license' for more information.
>>> import matplotlib
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/tmp/.mount_FreeCAKMeLzX/usr/lib/python3.6/site-packages/matplotlib/__init__.py", line 141, in <module>
    from . import cbook, rcsetup
  File "/tmp/.mount_FreeCAKMeLzX/usr/lib/python3.6/site-packages/matplotlib/rcsetup.py", line 29, in <module>
    from cycler import Cycler, cycler as ccycler
ModuleNotFoundError: No module named 'cycler'
>>> 
```

My system info:
OS: Fedora 26 (Workstation Edition)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.16207 (Git) AppImage
Build type: Release
Branch: master
Hash: 741533941c67da2f721bf1b7c2d55c987fd22a0c
Python version: 3.6.7
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/SouthAfrica (en_ZA)

Many thanks for your help!

**Comment by oliveroxtoby** [comment]
No longer seems to be an issue. Thanks.
