### ISSUE TITLE
Missing dependency of matplotlib

### ISSUE THREAD

**Issue by oliveroxtoby** [FreeCAD/FreeCAD-AppImage#18]
In the latest 0.18.1 candidate Appimage, the 'kiwisolver' package appears to be missing. This is a dependency of the Plot workbench via the matplotlib library. Plot workbench. Trying to load the Plot workbench in the python console, I get:
```
>>> from freecad.plot import Plot
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAWNgpYj/usr/lib/python3.7/site-packages/freecad/plot/Plot.py", line 34, in <module>
    import matplotlib.pyplot as plt
  File "/tmp/.mount_FreeCAWNgpYj/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/tmp/.mount_FreeCAWNgpYj/usr/lib/python3.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.gridspec as gridspec
  File "/tmp/.mount_FreeCAWNgpYj/usr/lib/python3.7/site-packages/matplotlib/gridspec.py", line 25, in <module>
    import matplotlib._layoutbox as layoutbox
  File "/tmp/.mount_FreeCAWNgpYj/usr/lib/python3.7/site-packages/matplotlib/_layoutbox.py", line 19, in <module>
    import kiwisolver as kiwi
ModuleNotFoundError: No module named 'kiwisolver'
```

**Comment by oliveroxtoby** [comment]
This sees to be sorted out now, thanks!

**Comment by oliveroxtoby** [comment]
I'm sorry, I spoke too soon. This is still an issue, for the latest 0.18.1 and 0.19 Appimages.

**Comment by oliveroxtoby** [comment]
Should be sorted out by commit f4959d4c846a2228a86e5c520354f9ab5d7c3a58
